[env:esp32cam] ; Aqui se define el environment para la placa ESP32-CAM
platform = espressif32 ; Aqui se especifica la plataforma de desarrollo, espressif32
board = esp32cam ; Se especifica el modelo de placa, en este caso es "esp32cam"
framework = arduino ; Se usara el framework de arduino
monitor_speed = 115200 ; Se establece la velocidad de comunicación para el monitor serie, en este caso es 115200 baudios.

