; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Esta línea arregla tu error rojo al subir el código:
upload_speed = 115200

; Esta línea te permite leer el láser en la terminal:
monitor_speed = 115200
lib_deps = ; Sección para definir las dependencias de las bibliotecas necesarias para el proyecto
	adafruit/Adafruit BNO055 @ ^1.6.3 ; Biblioteca para el sensor BNO055 de Adafruit
	adafruit/Adafruit_VL53L0X @ ^1.2.4 ; Biblioteca para el sensor de distancia VL53L0X de Adafruit
	pololu/QTRSensors @ ^4.0.0 ; Biblioteca para los sensores de línea QTR de Pololu
