; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1] ; Aqui se define el entorno de desarrollo para la placa ESP32 DOIT DevKit V1
platform = espressif32 ; Se especifica la plataforma de desarrollo, en este caso es para microcontroladores ESP32
board = esp32doit-devkit-v1 ; Es la placa específica que se está utilizando
framework = arduino ; Se indica que se utilizará el framework de Arduino para el desarrollo
monitor_speed = 115200 ; Velocidad de comunicación para el monitor serie
lib_deps = ; Sección para definir las dependencias de las bibliotecas necesarias para el proyecto
	adafruit/Adafruit BNO055 @ ^1.6.3 ; Biblioteca para el sensor BNO055 de Adafruit
	adafruit/Adafruit_VL53L0X @ ^1.2.4 ; Biblioteca para el sensor de distancia VL53L0X de Adafruit
	pololu/QTRSensors @ ^4.0.0 ; Biblioteca para los sensores de línea QTR de Pololu
