[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

upload_speed = 115200
monitor_speed = 115200

; Particion grande (3MB app) — necesaria porque Bluetooth Classic + WiFi/ESP-NOW
; ocupan mucho flash y no caben en la particion por defecto.
board_build.partitions = huge_app.csv

lib_ldf_mode = deep+
lib_deps =
    adafruit/Adafruit BNO055 @ ^1.6.3
    adafruit/Adafruit_VL53L0X @ ^1.2.4
    pololu/QTRSensors @ ^4.0.0
    SPI
    Wire
